org: sanjaym0512
app: hls-backend
service: hls-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true


functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  healthCheck:
    handler: index.healthCheck
    events:
      - httpApi:
          path: /healthCheck
          method: get
  createUser:
    handler: rest/Users/controller.createUser
    events:
      - httpApi:
          path: /createUser
          method: post
  login:
    handler: rest/Users/controller.login
    events:
      - httpApi:
          path: /login
          method: post
  getAllUsers:
    handler: rest/Users/controller.getAllUsers
    events:
      - httpApi:
          path: /getAllUsers
          method: get
  getAllProducts:
    handler: rest/Products/controller.getAllProducts
    events:
      - httpApi:
          path: /getAllProducts
          method: get
  getOneProduct:
    handler: rest/Products/controller.getOneProduct
    events:
      - httpApi:
          path: /products/{id}
          method: get
          cors: true
  checkout:
    handler: rest/Orders/controller.checkout
    events:
      - httpApi:
          path: /checkout
          method: post
  createOrder:
    handler: rest/Orders/controller.createOrder
    events:
      - httpApi:
          path: /createOrder
          method: post
  getAllOrders:
    handler: rest/Orders/controller.getAllOrders
    events:
      - httpApi:
          path: /getAllOrders
          method: get
plugins:
  - serverless-offline
